[colors.primary]
background = "#2c2a29"
foreground = "#d5c4a1"

[colors.normal]
black = "0x282828"
red = "0xcc241d"
green = "0x98971a"
yellow = "0xd79921"
blue = "0x458588"
magenta = "0xb16286"
cyan = "0x689d6a"
white = "0xa89984"

[colors.bright]
black = "0x928374"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xebdbb2"

[colors.selection]
text = "#ebdbb2"
background = "#3c3836"

[colors.cursor]
text = "#1d2021"
cursor = "#ebdbb2"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 12.0
offset = { x = 1, y = 0 }

[window]
blur = false
decorations = "none"
opacity = 0.9

[colors]
transparent_background_colors = false

[window.padding]
x = 8
y = 8
[keyboard]
bindings = [{ key = "Return", mods = "Alt", action = "ToggleFullscreen" }]

[env]
TERM = "tmux-256color"
STARSHIP_CONFIG = "/home/tiramisu_cake/.config/alacritty/starship.toml"

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session"]
