[colors.normal]
black = "0x282C34"
blue = "0x61AFEF"
cyan = "0x56B6C2"
green = "0x98C379"
magenta = "0xC678DD"
red = "0xE06C75"
white = "0xABB2BF"
yellow = "0xE5C07B"

[colors.primary]
background = "0x000000"
foreground = "0xF8F8F8"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size   = 12.0
offset = { x = 1, y = 0 }

[window]
blur = true
decorations = "none"
opacity = 0.8

[window.padding]
x = 8
y = 8
[keyboard]
bindings = [
  { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
]

[env]
TERM = "tmux-256color"

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "/usr/local/bin/tmux"
args = ["new-session", "-A", "-s", "terminal"]
