[colors.normal]
black = "0x282C34"
blue = "0x61AFEF"
cyan = "0x56B6C2"
green = "0x98C379"
magenta = "0xC678DD"
red = "0xE06C75"
white = "0xABB2BF"
yellow = "0xE5C07B"

[colors.primary]
background = "#1d2021" # или "#282828" / "#32302f"
foreground = "#ebdbb2"

[colors.selection]
text = "#ebdbb2"
background = "#3c3836"

[colors.cursor]
text = "#1d2021"
cursor = "#ebdbb2"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 12.0
offset = { x = 1, y = 0 }

[window]
blur = false
decorations = "none"
opacity = 0.9

[colors]
transparent_background_colors = false

[window.padding]
x = 8
y = 8
[keyboard]
bindings = [{ key = "Return", mods = "Alt", action = "ToggleFullscreen" }]

[env]
TERM = "tmux-256color"
STARSHIP_CONFIG = "/home/tiramisu_cake/.config/alacritty/starship.toml"

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session"]
