# === Gruvbox vibe ===========================================================
palette = "gruvbox_dark"

[palettes.gruvbox_dark]
bg0 = "#282828"
bg1 = "#3c3836"
bg2 = "#504945"
fg0 = "#fbf1c7"
fg1 = "#ebdbb2"
fg2 = "#d5c4a1"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
purple = "#d3869b"
aqua = "#8ec07c"
orange = "#fe8019"
gray = "#928374"

# 1) Корневой формат: порядок модулей и «скобки» в gruvbox-сером
format = """
[╭─ ](fg:gray)$directory$git_branch$git_status$git_state
[╰─ ](fg:gray)$character
"""

# 2) username — нейтрально, читабельно
[username]
format = "[$user]($style) "
show_always = true
style_user = "bold fg:fg1"
style_root = "bold fg:red"

# 3) directory — «пилюля» в gruvbox-aqua, текст тёмный как в теме
[directory]
truncation_length = 0
truncate_to_repo = false
read_only = "  "
# сам «пилюльный» сегмент
style = "bg:aqua fg:bg0"
read_only_style = "bg:aqua fg:bg0"
format = "[](fg:aqua)[$read_only$path]($style)[](fg:aqua) "

# 4) Ветка Git — тёпло-жёлтая
[git_branch]
symbol = " "
style = "fg:yellow"
format = "[$symbol$branch]($style) "

# 5) Состояние Git — фиолетовый акцент
[git_state]
style = "fg:purple"
format = "[$state( $progress)]($style) "

# 6) Статусы Git целиком — чуть более спокойные (оранжевый)
[git_status]
style = "fg:orange"

# 7) Символ приглашения — gruvbox-зеленый/красный
[character]
success_symbol = "[✔](fg:green) "
error_symbol = "[✖](fg:red) "

# 8) Python-модуль отключён (как и было)
[python]
disabled = true
